// Llama método -> escribe en doument (Objeto) el resto de información disponible del navegador.
document.write("<p>")
document.write("Información del navegador:")
document.write("<br>")
document.write("Versión: ")
document.write(infoNav.version)
document.write("<br>")
document.write("Plataforma: ")
document.write(infoNav.plataforma)
document.write("<br>")
document.write("Vendedor: ")
document.write(infoNav.vendedor)
document.write("<br>")
document.write("Agente: ")
document.write(infoNav.agente)
document.write("<br>")
document.write("JavaActivo: ")
document.write(infoNav.javaActivo)
document.write("<br>")
document.write("</p>")